### ISSUE TITLE
Engine is a singleton without the protections thereof.

### ISSUE THREAD

**Issue by Delwin9999** [bonesoul/voxeliq#43]
Engine has the private static _instance attribute and assignment to this of a singleton but the constructor is public.  This means someone could instantiate it twice thinking they'd get the same instance (as you would with a real singleton) but in fact they'd overwrite the first one's _instance with the second one and the game state would be unrecoverable.

This should be a real singleton pattern.  The only reason it isn't right now is that the unit tests fail when I tried to do the conversion on my branch.  When I become more familiar with the unit test harness I will be able to untangle that and I can throw a pull request for the fix at you.

**Comment by bonesoul** [comment]
Yes, I had thrown some random _instances' all over the code, which should only exists for the Engine.cs itself and you are right, that singleton have to be fixed.

So I think actual singleton should be like;

```
    private static Engine _instance =new Engine(); // the instance.

    /// <summary>
    /// Returns the memory instance of Engine.
    /// </summary>
    public static Engine Instance
    {
        get { return _instance; }
    }
```

and the Engine should have private static constructor.

Then we have to find another method to let config to be attached that could be similar to something like;

```
    public void Run(Game game, EngineConfiguration config)
    { 
                this.Game = game;
                this.Configuration = config;

                config.Validate(); // validate the config.
    }
```

Update: 
mm, you are right that will break how tests works - ie the ChunkStorageTests.
So maybe we can just fix the problem temp. until we sort out all the stuff - https://github.com/raistlinthewiz/voxeliq/commit/9235b2e40f8e9762a3f6c2b462f648d23157af1e

**Comment by bonesoul** [comment]
this eventually fails the tests too;

http://voxeliq-ci.cloudapp.net/viewLog.html?buildId=122&tab=buildResultsDiv&buildTypeId=bt2

**Comment by bonesoul** [comment]
I've further worked on the issue and I think in an library (or in our case the engine) using singletons is all evil. So I'll be further re-factoring them out as much as I can. Maybe be we could let Engine.Instance stay until we find a better solution working for both the library itself and the tests.

**Comment by bonesoul** [comment]
Only Rasterizer.Instance left now other than Engine.Instance which later needs more work.

**Comment by bonesoul** [comment]
- [x] https://github.com/raistlinthewiz/voxeliq/commit/563789e8f98b41765771141658e5b55c81711c57 SettingsReaders are no more singletons.
- [x] https://github.com/raistlinthewiz/voxeliq/commit/e6b7e79666aa04d029134f0ee8cb3ec54c9b9e6f AssetManager fixed.
- [x] https://github.com/raistlinthewiz/voxeliq/commit/87ffdbd45850b440389b6eef9c7b8d625b894587 ChunkStorage and InputManager fixed.
- [x] https://github.com/raistlinthewiz/voxeliq/commit/449823bac2f36d5abfc5704871284afcc04a876a - Fix Rasterizer.Instance.

**Comment by bonesoul** [comment]
Further architectural discussion: #50
